<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCEYhbGz\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCEYhbGz/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCEYhbGz.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCEYhbGz\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCEYhbGz\App_KernelDevDebugContainer([
    'container.build_hash' => 'CEYhbGz',
    'container.build_id' => '1a8e3855',
    'container.build_time' => 1613209283,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCEYhbGz');
